---
title: "Vis I"
author: "Yucheng Zhao"
date: "2024-09-29"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(ggridges)
```

weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())





```{r}
weather_df = read_csv("weather_df.csv") 

weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3) + 
  labs(title = "Temperature scatterplot",
       x = "Min. Temp (C)",
       y = "max. Temp (C)",
       color = "location",
       caption = ("Weather data taken from rnoaa package for threee stations")
  ) +
  viridis::scale_color_viridis(discrete = TRUE)
```




```{r}

```




```{r}

```



```{r}

```



```{r}

```




